//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MwLanguageServer.Localizable {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Diagnostics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diagnostics() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MwLanguageServer.Localizable.Diagnostics", typeof(Diagnostics).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Duplate tag attribute &quot;{0}&quot; in &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string DuplicateTagAttribute {
            get {
                return ResourceManager.GetString("DuplicateTagAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate template argument &quot;{0}&quot; in &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string DuplicateTemplateArgument {
            get {
                return ResourceManager.GetString("DuplicateTemplateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty transclusion target. 的本地化字符串。
        /// </summary>
        internal static string EmptyTransclusionTarget {
            get {
                return ResourceManager.GetString("EmptyTransclusionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty Wikilink target. 的本地化字符串。
        /// </summary>
        internal static string EmptyWikilinkTarget {
            get {
                return ResourceManager.GetString("EmptyWikilinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open tag is implicitly closed by end of line. 的本地化字符串。
        /// </summary>
        internal static string OpenTagClosedByEndOfLine {
            get {
                return ResourceManager.GetString("OpenTagClosedByEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open tag &quot;{0}&quot; is not closed. 的本地化字符串。
        /// </summary>
        internal static string OpenTagNotClosed {
            get {
                return ResourceManager.GetString("OpenTagNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transclusion expression &quot;{0}&quot; is not closed. 的本地化字符串。
        /// </summary>
        internal static string TransclusionNotClosed {
            get {
                return ResourceManager.GetString("TransclusionNotClosed", resourceCulture);
            }
        }
    }
}
