//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MwLanguageServer.Localizable {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MwLanguageServer.Localizable.Prompts", typeof(Prompts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Argument Reference 的本地化字符串。
        /// </summary>
        internal static string ArgumentReferenceNode {
            get {
                return ResourceManager.GetString("ArgumentReferenceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Link 的本地化字符串。
        /// </summary>
        internal static string ExternalLinkNode {
            get {
                return ResourceManager.GetString("ExternalLinkNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Switch 的本地化字符串。
        /// </summary>
        internal static string FormatSwitchNode {
            get {
                return ResourceManager.GetString("FormatSwitchNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inferred page information. 的本地化字符串。
        /// </summary>
        internal static string InferredPageInfo {
            get {
                return ResourceManager.GetString("InferredPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italics 的本地化字符串。
        /// </summary>
        internal static string Italics {
            get {
                return ResourceManager.GetString("Italics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  or  的本地化字符串。
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redirect:  的本地化字符串。
        /// </summary>
        internal static string RedirectColon {
            get {
                return ResourceManager.GetString("RedirectColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Argument 的本地化字符串。
        /// </summary>
        internal static string TemplateArgumentNode {
            get {
                return ResourceManager.GetString("TemplateArgumentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magic Word 的本地化字符串。
        /// </summary>
        internal static string TemplateMagicNode {
            get {
                return ResourceManager.GetString("TemplateMagicNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Transclusion 的本地化字符串。
        /// </summary>
        internal static string TemplateNode {
            get {
                return ResourceManager.GetString("TemplateNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage:  的本地化字符串。
        /// </summary>
        internal static string UsageColon {
            get {
                return ResourceManager.GetString("UsageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wiki Link 的本地化字符串。
        /// </summary>
        internal static string WikiLinkNode {
            get {
                return ResourceManager.GetString("WikiLinkNode", resourceCulture);
            }
        }
    }
}
